[package]
name = "hyperspace-solana"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitives = { path = "../primitives", package = "hyperspace-primitives" }

# crates.io
anyhow = "1.0.65"
futures = "0.3.21"
async-trait = "0.1.53"
log = "0.4.17"
hex = "0.4.3"
tokio = { version = "1.32.0", features = ["macros", "sync"] }
rs_merkle = "1.2.0"
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
serde_json = "1.0.74"
derive_more = { version = "0.99", features = ["from"]  }
serde = {version="1.0.137", features = ["derive"]}
tokio-stream = { version = "0.1.14", features = ["sync"]}
thiserror = "1.0.31"
itertools = "0.10.3"
prost = { version = "0.11" }
k256 = { version = "0.11.6", features = ["ecdsa-core", "ecdsa", "sha256"] }
tonic = { version = "0.8", features = ["tls", "tls-roots"] }
bech32 = "0.9.1"
bip32 = "0.4.0"
ed25519-zebra = { version = "3.1.0" }
tiny-bip39 = "1.0.0"
sha2 = "0.10.6"
ripemd = "0.1.3"
digest = "0.10.6"
quick_cache = "0.3.0"
rand = "0.8.5"
anchor-client = "0.29.0"
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
solana-transaction-status = "1.16.18"
base64 = "0.21.4"
borsh = { version = "0.10.3", default-features = false }

# composable
ibc = { version = "0.47.0", default-features = false, features = ["borsh", "serde"],package="ibc" }
ibc-proto = { version = "0.37.1", default-features = false, package="ibc-proto" }
# ibc = { path = "../../ibc/modules", features = [] }
ibc-proto-old = { path = "../../ibc/proto", package="ibc-proto" }
ibc-primitives = { path = "../../contracts/pallet-ibc/primitives" }
# ics07-tendermint = { path = "../../light-clients/ics07-tendermint" }
# ics08-wasm = { path = "../../light-clients/ics08-wasm" }
ibc-rpc = { path = "../../contracts/pallet-ibc/rpc" }
pallet-ibc = { path = "../../contracts/pallet-ibc" }


# Trie
lib = { git = "https://github.com/ComposableFi/emulated-light-client.git" }
# lib = { path = "../../../emulated-light-client/common/lib" }
memory = { git = "https://github.com/ComposableFi/emulated-light-client.git" }
sealable-trie = { git = "https://github.com/ComposableFi/emulated-light-client.git", features = ["borsh"] }
stdx = { git = "https://github.com/ComposableFi/emulated-light-client.git" }
solana-trie = { git = "https://github.com/ComposableFi/emulated-light-client.git" }

#Contract
solana-ibc = { git = "https://github.com/ComposableFi/emulated-light-client.git", branch="mpn/d", features = ["mocks"]}
# solana-ibc = { path = "../../../emulated-light-client/solana/solana-ibc/programs/solana-ibc", features = ["mocks"]}

tracing = "0.1.36"

# tendermint
tendermint = { git = "https://github.com/informalsystems/tendermint-rs", rev = "e81f7bf23d63ffbcd242381d1ce5e35da3515ff1", default-features = false, features = [
    "secp256k1",
] }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", rev = "e81f7bf23d63ffbcd242381d1ce5e35da3515ff1", default-features = false }
tendermint-rpc = { git = "https://github.com/informalsystems/tendermint-rs", rev = "e81f7bf23d63ffbcd242381d1ce5e35da3515ff1", default-features = false, features = [
    "http-client",
    "websocket-client",
] }
tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", rev = "e81f7bf23d63ffbcd242381d1ce5e35da3515ff1", default-features = false, features = [
    "rpc-client",
    "secp256k1",
    "unstable",
#    "testing"
] }
tendermint-light-client-verifier = { git = "https://github.com/informalsystems/tendermint-rs", rev = "e81f7bf23d63ffbcd242381d1ce5e35da3515ff1", default-features = false }

[features]
testing = [
    "primitives/testing"
]